import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { BookOpen, Sparkles, Square, RotateCcw, Download } from 'lucide-react';
import { gemini } from '../services/gemini';
import { cn } from '../lib/utils';
import type { StoryChunk } from '../services/gemini';

interface StoryPart {
  type: 'text' | 'image';
  content: string;
}

interface StoryboardCreatorProps {
  brandVoice: string;
}

/**
 * StoryboardCreator — the Creative Storyteller feature.
 *
 * Uses Gemini's interleaved TEXT + IMAGE output (responseModalities: [TEXT, IMAGE])
 * to stream a full campaign storyboard where scene narration and generated visuals
 * arrive in a single, fluent response stream — no separate requests.
 *
 * This is the mandatory "interleaved/mixed output" capability for the
 * Creative Storyteller hackathon category.
 */
export const StoryboardCreator: React.FC<StoryboardCreatorProps> = ({ brandVoice }) => {
  const [concept, setConcept] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [storyParts, setStoryParts] = useState<StoryPart[]>([]);
  const [error, setError] = useState<string | null>(null);
  const abortRef = useRef(false);
  const outputRef = useRef<HTMLDivElement>(null);

  const handleGenerate = async () => {
    if (!concept.trim() || isGenerating) return;

    setIsGenerating(true);
    setStoryParts([]);
    setError(null);
    abortRef.current = false;

    try {
      const generator = gemini.generateStoryboard(concept, brandVoice);

      for await (const chunk of generator) {
        if (abortRef.current) break;

        setStoryParts(prev => {
          // For text chunks: append to the last text part if it exists, else create new
          if (chunk.type === 'text') {
            if (prev.length > 0 && prev[prev.length - 1].type === 'text') {
              const updated = [...prev];
              updated[updated.length - 1] = {
                type: 'text',
                content: (updated[updated.length - 1] as StoryPart & { type: 'text' }).content + chunk.content,
              };
              return updated;
            }
            return [...prev, { type: 'text', content: chunk.content }];
          }
          // For image chunks: always append as a new image part
          return [...prev, { type: 'image', content: chunk.content }];
        });

        // Auto-scroll as content streams in
        setTimeout(() => {
          outputRef.current?.scrollTo({ top: outputRef.current.scrollHeight, behavior: 'smooth' });
        }, 50);
      }
    } catch (err) {
      console.error('Storyboard generation failed:', err);
      setError('Generation failed. The interleaved image model may not be available with your current API key. Try a different prompt or check your API quota.');
    } finally {
      setIsGenerating(false);
      abortRef.current = false;
    }
  };

  const handleStop = () => {
    abortRef.current = true;
    setIsGenerating(false);
  };

  const handleReset = () => {
    abortRef.current = true;
    setIsGenerating(false);
    setStoryParts([]);
    setError(null);
    setConcept('');
  };

  const handleDownload = () => {
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Prism AI Storyboard — ${concept}</title>
<style>
  body { font-family: Georgia, serif; max-width: 900px; margin: 0 auto; padding: 40px; background: #0a0a0a; color: #e5e5e5; }
  h1 { font-size: 2rem; border-bottom: 2px solid #ff4e00; padding-bottom: 1rem; }
  .meta { color: #888; font-size: 0.85rem; margin-bottom: 2rem; }
  .text { line-height: 1.8; margin: 1.5rem 0; white-space: pre-wrap; }
  img { width: 100%; border-radius: 12px; margin: 1.5rem 0; }
</style>
</head>
<body>
<h1>Campaign Storyboard</h1>
<div class="meta">Concept: ${concept} &nbsp;|&nbsp; Brand Voice: ${brandVoice} &nbsp;|&nbsp; Generated by Prism AI</div>
${storyParts.map(p =>
  p.type === 'text'
    ? `<div class="text">${p.content.replace(/</g, '&lt;')}</div>`
    : `<img src="${p.content}" alt="storyboard scene" />`
).join('\n')}
</body>
</html>`;
    const blob = new Blob([html], { type: 'text/html' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `storyboard-${Date.now()}.html`;
    a.click();
  };

  const imageCount = storyParts.filter(p => p.type === 'image').length;
  const hasContent = storyParts.length > 0;

  return (
    <div className="flex flex-col gap-6 w-full">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-brand-primary/10 flex items-center justify-center">
          <BookOpen className="w-5 h-5 text-brand-primary" />
        </div>
        <div>
          <h3 className="font-bold text-lg leading-tight">Storyboard Creator</h3>
          <p className="text-[10px] uppercase tracking-[0.2em] text-text-muted font-mono">
            Interleaved Text + Image Output
          </p>
        </div>
        <div className="ml-auto flex items-center gap-2 px-3 py-1 bg-brand-primary/10 rounded-full border border-brand-primary/20">
          <div className="w-1.5 h-1.5 rounded-full bg-brand-primary animate-pulse" />
          <span className="text-[10px] font-mono uppercase tracking-widest text-brand-primary">Live Stream</span>
        </div>
      </div>

      {/* Concept Input */}
      <div className="flex flex-col gap-3">
        <label className="text-[10px] uppercase tracking-widest text-text-muted font-mono">Campaign Concept</label>
        <textarea
          value={concept}
          onChange={e => setConcept(e.target.value)}
          disabled={isGenerating}
          placeholder="e.g. A sustainable sneaker brand targeting Gen Z urban athletes who care about both performance and the planet..."
          className="w-full h-24 bg-glass border border-glass-border rounded-2xl p-4 text-sm focus:outline-none focus:border-brand-primary/50 transition-all resize-none disabled:opacity-50"
        />
        <div className="flex gap-3">
          <button
            onClick={isGenerating ? handleStop : handleGenerate}
            disabled={!isGenerating && !concept.trim()}
            className={cn(
              "flex-1 py-3 font-bold rounded-2xl transition-all flex items-center justify-center gap-2 text-sm",
              isGenerating
                ? "bg-red-500/20 border border-red-500/30 text-red-400 hover:bg-red-500/30"
                : "bg-brand-primary hover:bg-brand-primary/90 disabled:opacity-40 text-white shadow-lg shadow-brand-primary/20"
            )}
          >
            {isGenerating ? (
              <>
                <Square className="w-4 h-4" />
                Stop Generation
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                Generate Storyboard
              </>
            )}
          </button>
          {hasContent && !isGenerating && (
            <button
              onClick={handleDownload}
              className="px-4 py-3 bg-glass border border-glass-border rounded-2xl text-text-secondary hover:text-[var(--text)] hover:border-brand-primary/30 transition-all"
              title="Download as HTML"
            >
              <Download className="w-4 h-4" />
            </button>
          )}
          {hasContent && !isGenerating && (
            <button
              onClick={handleReset}
              className="px-4 py-3 bg-glass border border-glass-border rounded-2xl text-text-secondary hover:text-[var(--text)] transition-all"
              title="Reset"
            >
              <RotateCcw className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {/* Error State */}
      <AnimatePresence>
        {error && (
          <motion.div
            initial={{ opacity: 0, y: -8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            className="p-4 bg-red-500/10 border border-red-500/20 rounded-2xl text-red-400 text-sm"
          >
            {error}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Streaming Output */}
      <AnimatePresence>
        {(hasContent || isGenerating) && (
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 16 }}
            className="flex flex-col"
          >
            {/* Stats bar */}
            <div className="flex items-center justify-between mb-4 px-1">
              <span className="text-[10px] font-mono uppercase tracking-widest text-text-muted">
                Interleaved Output Stream
              </span>
              <div className="flex items-center gap-4">
                {imageCount > 0 && (
                  <span className="text-[10px] font-mono text-brand-primary">
                    {imageCount} scene{imageCount !== 1 ? 's' : ''} rendered
                  </span>
                )}
                {isGenerating && (
                  <motion.div
                    animate={{ opacity: [0.4, 1, 0.4] }}
                    transition={{ duration: 1.2, repeat: Infinity }}
                    className="flex items-center gap-1.5"
                  >
                    <div className="w-1.5 h-1.5 rounded-full bg-brand-primary" />
                    <span className="text-[10px] font-mono text-brand-primary uppercase tracking-widest">streaming</span>
                  </motion.div>
                )}
              </div>
            </div>

            {/* Story content */}
            <div
              ref={outputRef}
              className="glass-panel p-6 max-h-[600px] overflow-y-auto custom-scrollbar flex flex-col gap-5 border-brand-primary/10"
            >
              {storyParts.map((part, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3 }}
                >
                  {part.type === 'text' ? (
                    <p className="text-text-secondary leading-relaxed text-sm whitespace-pre-wrap">
                      {part.content}
                    </p>
                  ) : (
                    <div className="rounded-2xl overflow-hidden border border-brand-primary/10 group relative">
                      <img
                        src={part.content}
                        alt="Generated storyboard scene"
                        className="w-full object-cover aspect-video group-hover:scale-[1.02] transition-transform duration-500"
                      />
                      <div className="absolute bottom-3 right-3 px-2 py-1 bg-black/60 backdrop-blur-sm rounded-lg">
                        <span className="text-[9px] font-mono uppercase tracking-widest text-white/60">
                          Gemini 2.0 Flash Generated
                        </span>
                      </div>
                    </div>
                  )}
                </motion.div>
              ))}

              {/* Streaming cursor */}
              {isGenerating && (
                <motion.div
                  animate={{ opacity: [0, 1, 0] }}
                  transition={{ duration: 0.8, repeat: Infinity }}
                  className="w-2 h-5 bg-brand-primary rounded-sm"
                />
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Empty state hint */}
      {!hasContent && !isGenerating && !error && (
        <div className="text-center py-8 border border-dashed border-glass-border rounded-2xl">
          <BookOpen className="w-8 h-8 text-text-muted mx-auto mb-3 opacity-40" />
          <p className="text-xs text-text-muted font-mono uppercase tracking-widest opacity-50">
            Describe a campaign concept to generate<br />an AI storyboard with interleaved visuals
          </p>
        </div>
      )}
    </div>
  );
};
